#! /bin/sh

# MONITOR SETUP
$HOME/init_bspwm/display.sh

# WALLPAPER BY "feh"
# command : feh --bg-scale filepath_1 filepath_2 (for multi monitor)
# To make it default for every session :
~/.fehbg

# AUTOSTART
picom -f &
setxkbmap de &

# KEYBINDINGS SETTING
pgrep -x sxhkd > /dev/null || sxhkd &

# POLYBAR SETUP
$HOME/.config/polybar/launch.sh

# WORKSPACE SETUP
bspc monitor DP-1  -d I II III IV V VI VII 
bspc monitor eDP-1 -d VIII IX X

# WINDOW SIZE SETTING
bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# WINDOW RULE
# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Cawbird desktop='^8' state=floating rectangle=800x1000+1025+125
